// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "dahood-20181104101721--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://dahood-20181104101721--hostingbucket.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
